apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    name: simple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
      - containerPort: 8080
    envFrom:
      - secretRef:
          name: app-secret

    env:
      - name: DB_Password
        valueFrom:
          SecretKeyRef:
            name: app-secret
            key: DB_Password

    volumes:
      - name: app-secret-volume
        Secret:
          secretName: app-secret

