apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-01T21:43:00Z"
  labels:
    run: bee
  name: bee
  namespace: default
  resourceVersion: "1861"
  uid: 93dd28b8-6027-4a14-9537-e71f89750603
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: bee
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-znqfz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: "NoSchedule"
    key: "spray"
    operator: "Equal"
    value: "mortein"