apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-06-26T20:58:39Z"
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default
  resourceVersion: "940"
  uid: 338979ee-97dc-4567-b075-e0c9987df8da
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    envFrom:
      - secretRef:
          name: db-secret