---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datacenter.traffic.controller
spec:
  group: traffic.controller
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dataField:
                  type: integer
                access:
                  type: boolean
  scope: Namespaced
  names:
    plural: datacenter
    singular: datacenter
    kind: datacenter
    shortNames:
    - dc