apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  label:
    name: simple-webapp
spec:
  containers:
    - name: simple-webapp
      image: simple-webapp
      ports:
        - containerPort: 8080

    - name: log-agent
      image: log-agent
    # Design Patterns
    # - Sidecar: For example a log collection agent container
    # - Adapter: For example a log collector which collects and formats the log messages into a unified format
    # - Ambassador: For example a container which is responsible to know which database instance to connect to according to env, dev, prod, testing while providing a single interface