apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-05T21:29:27Z"
  labels:
    name: simple-webapp
  name: simple-webapp-1
  namespace: default
  resourceVersion: "1727"
  uid: 3ce3ed41-d7d2-4f08-ba88-de2b5720c6f2
spec:
  containers:
  - image: kodekloud/webapp-delayed-start
    imagePullPolicy: Always
    name: simple-webapp
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /live
        port: 8080
      initialDelaySeconds: 80
      periodSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-672gh
      readOnly: true